---
- exe-paths:
    - 'torbrowser_firefox'
  users:
    - 'amnesia'
  commands:
    SIGNAL:
      - 'NEWNYM'
    GETINFO:
      - 'circuit-status'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
  confs:
    bridge:
  events:
    STREAM:
  restrict-stream-events: true
