---
- match-exe-paths:
    - '/usr/bin/onioncircuits'
  match-users:
    - 'amnesia'
  commands:
    GETINFO:
      - 'version'
      - 'circuit-status'
      - 'stream-status'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
    GETCONF:
      - 'usemicrodescriptors'
      - '__owningcontrollerprocess'
  events:
    SIGNAL:
      suppress: true
    CONF_CHANGED:
      suppress: true
    STREAM:
    CIRC:
